- app/models/MediaItemLiveStream.php
eloquent whereIsNull corrected to whereNull
> sql query fix

- app/assets/scripts/app/components/player.js
This is the same form as the text on the homepage carousel.
> Player now shows "Tomorrow" and "Today" in ad instead of date.

- app/assets/css/app/videojs.css
- app/assets/css/bootstrap/embed.css
- app/assets/css/bootstrap/home.css
- app/assets/scripts/app/components/player-container.js
- app/assets/scripts/app/pages/embed/player-page.js
- app/assets/scripts/app/pages/home/player-page.js
- app/assets/scripts/app/player-controller.js
- app/controllers/home/player/PlayerController.php
- app/views/home/player/index.php
> User can now provide player start time in url on main site

- app/commands/MediaItemEmailsSendLiveShortlyCommand.php
- app/jobs/MediaItemLiveEmailJob.php
> Live and Live Shortly emails will now only be sent once every 40 mins

- app/assets/css/app/pages/home/side-banners.css
- app/assets/css/app/pages/home/sticky-footer.css
- app/assets/scripts/app/device-detection.js
- app/assets/scripts/app/pages/home/side-banners.js
> Side banners no longer shown on mobile devices

- app/assets/scripts/app/components/player.js
- app/assets/scripts/app/pages/embed/player-page.js
- app/assets/scripts/app/pages/home/auto-continue-manager.js
- app/assets/scripts/app/player-controller.js
> Merging in embeddable player javascript api

- app/commands/DvrBridgeServiceSendPingsCommand.php
- app/filters.php
- app/models/MediaItemLiveStream.php
> Added embeddable player javascript api

- docs/Embeddable Player.md
> Created documentation for embeddable player

- app/assets/scripts/app/components/player.js
This prevents cover art getting removed
> VOD player seek to start point now only occurs when not 0

- app/assets/css/app/bootstrap-modal.css
- app/assets/css/app/components/share-modal.css
- app/assets/css/bootstrap/admin.css
- app/assets/css/bootstrap/embed.css
- app/assets/css/bootstrap/home.css
- app/assets/scripts/app/components/alert-modal.js
- app/assets/scripts/app/components/player-container.js
Facebook's mobile browser was ignoring alert() calls
> Login required message is now bootstrap modal instead of alert()

- app/views/home/admin/livestreams/index.php
Before if user didn't have the edit permission then the button wasn't visible.
> Watch link in livestreams in cms is now always accessible

- app/controllers/home/player/PlayerController.php
will revert this if facebook starts supporting it
> removed og:video_url tags with link for iframe because facebook still not supporting properly

- app/assets/scripts/app/pages/home/playlist.js
when the jquery hover event was used the click event wouldn't get picked up sometimes
> disabled cover art hover animation on mobiles to fix click issue

- app/assets/css/app/pages/home/zoom-animation.css
goes a bit funny on ios when scrolling
> disabled cover art zoom animation on mobiles

- .gitignore
- app/assets/scripts/app/components/player.js
- app/config/custom.php
- app/controllers/home/HomeBaseController.php
- app/controllers/home/HomeController.php
- app/controllers/home/contact/ContactController.php
- app/controllers/home/guide/GuideController.php
- app/controllers/home/liveStream/LiveStreamController.php
- app/controllers/home/player/PlayerController.php
- app/controllers/home/playlist/PlaylistController.php
- app/controllers/home/show/ShowController.php
Homepage now also has twitter properties
> Added twitter card properties to contact and guide pages

- app/assets/scripts/app/pages/home/live-stream-page.js
Player was broken because forgot to update parameters.
> Fix live stream page

- app/assets/css/app/pages/home/player-page.css
> Fix so that text in jump to series button will wrap

- app/assets/scripts/app/pages/home/player-page.js
- app/assets/scripts/bootstrap/home.js
- app/assets/scripts/lib/jquery.visible.js
> Player now scrolls into view when chapter clicked if necessary

- app/assets/scripts/app/components/comments.js
- app/controllers/home/player/PlayerController.php
> URLs in comments now converted to hyperlinks

- app/assets/scripts/app/pages/home/player-page.js
- app/models/MediaItemLiveStream.php
Also minor fix for scrolling when clicking on chapter.
> Fix eloquent issue when using live stream "live", "notLive" and "show Over" scopes

- app/assets/scripts/app/components/player.js
- app/assets/scripts/app/player-controller.js
> Setting video preload back to auto and switch play and seek to handle safari issues

- app/assets/css/app/components/ajax-upload.css
- app/assets/scripts/app/components/ajax-upload.js
- app/serviceProviders/upload/UploadManager.php
> Source files can now be downloaded easily from the cms (when user has permission)

- app/assets/scripts/lib/clappr.js
Also fixed so that compatible with requirejs
> Updated clappr to version with hlsjs support

- app/assets/scripts/lib/clappr.js
There are still some issues that need fixing with dvr.
> Reverting back to clappr v0.2.13

- app/assets/css/app/delay-show.css
- app/assets/css/bootstrap/embed.css
- app/assets/css/bootstrap/home.css
- app/views/embed/player.php
Prevents it flickering on and off before video fades in on embeddable player.
> Player message now fades in after delay so not shown if not necessary

- app/assets/scripts/app/pages/embed/player-page.js
> Full screen button now hidden automatically if detects can't go full screen

- app/serviceProviders/upload/UploadManager.php
Move fails on linux when moving from a local disc to a cifs share.
> UploadManager now falls back to a copy and delete if  move fails

- app/assets/css/app/pages/home/side-banners.css
- app/assets/scripts/app/pages/home/side-banners.js
Gradient is now to black instead of white.
> Side banners colour tweak

- app/assets/scripts/app/components/player.js
Player no longer reloads when this happens.
Closes #668
> Player component now handles live stream switching from live to ended

- app/assets/scripts/app/components/player.js
They aren't working on some devices and don't know why yet. When #628 is complete this may no longer be an issue.
> VOD HLS streams now filtered out for android devices

- app/assets/scripts/app/google-analytics.js
- app/assets/scripts/app/pages/home/twitter-timeline.js
Should no longer hold up rest of the page if take ages to download, or have to timeout.
> Google analytics and twitter lib now loaded in asynchronously

- app/commands/MediaItemEmailsSendVodAvailableCommand.php
> New message for vod available email when been live

- app/assets/scripts/app/components/player.js
- app/assets/scripts/lib/clappr.js
https://github.com/LA1TV/Website/issues/685
> Temporary hack so start time works

- .env.local.php.sample
- .env.php.sample
- app/assets/scripts/app/notification-service.js
- app/assets/scripts/app/player-controller.js
- app/assets/scripts/lib/socket.io.js
- app/config/notificationService.php
- app/controllers/embed/EmbedBaseController.php
- app/controllers/home/HomeBaseController.php
- app/events.php
- app/notifications/MediaItemLiveHandler.php
- composer.json
> Player will now update immediately when receives notification from notification service

- app/filters.php
This prevents that exception being logged.
> TokenMismatchException now handled

- app/assets/scripts/app/pages/home/browser-notification-manager.js
Used with initial test notification when enabled
> Add fallback notification icon

- app/assets/scripts/app/components/player.js
This reverts commit 113134f5f6d44a319608c44f2f2c77cfdc52959a.
> Revert "Remove seek hack (now fixed in hlsjs)"

- .env.php.sample
- app/api/ApiResponseDataGenerator.php
- app/assets/css/app/pages/home/degraded-service-bar.css
- app/assets/css/app/pages/home/notification-bar.css
- app/assets/css/bootstrap/home.css
- app/assets/scripts/app/pages/home/degraded-service-bar.js
- app/assets/scripts/app/pages/home/notification-priorities.js
- app/assets/scripts/bootstrap/home.js
- app/commands/CheckFileStoreAvailabilityCommand.php
- app/config/degradedService.php
- app/controllers/embed/EmbedBaseController.php
- app/controllers/home/HomeBaseController.php
- app/controllers/home/HomeController.php
- app/controllers/home/admin/upload/UploadController.php
- app/controllers/home/liveStream/LiveStreamController.php
- app/controllers/home/player/PlayerController.php
- app/controllers/home/playlist/PlaylistController.php
- app/controllers/home/playlists/PlaylistsController.php
- app/controllers/home/show/ShowController.php
- app/controllers/home/shows/ShowsController.php
- app/filters.php
- app/models/MediaItem.php
- app/start/artisan.php
- app/views/home/degradedIndex.php
> Implemented degraded service mode

- app/config/permissions.php
- app/controllers/home/admin/AdminBaseController.php
- app/controllers/home/admin/apiUsers/ApiUsersBaseController.php
- app/controllers/home/admin/apiUsers/ApiUsersController.php
- app/database/seeds/PermissionGroupSeeder.php
- app/database/seeds/PermissionSeeder.php
- app/models/ApiUser.php
- app/routes.php
- app/views/home/admin/apiUsers/edit.php
- app/views/home/admin/apiUsers/index.php
- app/views/layouts/home/admin/master.blade.php
> Added API Users section to CMS

- app/assets/src/app/components/cookie-compliance-modal.js
> CookieComplianceModal fix. Wait for dom to be ready

- app/api/ApiResponseDataGenerator.php
- app/api/transformers/MediaItemTransformer.php
- app/controllers/api/v1/ApiController.php
- app/models/File.php
- docs/API.md
> Added vod processing information to API

- app/controllers/api/ApiBaseController.php
- app/models/PlaybackHistory.php
- app/serviceProviders/smartCache/SmartCacheManager.php
- app/serviceProviders/smartCache/SmartCacheQueueJob.php
- composer.json
> Updated smart cache to use PredisMutex, take a closure, and view counts and watching now's use SmartCache

- app/assets/src/app/components/player.js
- app/assets/src/lib/clappr.js
> Clappr update with back to live fix, and default is now hlsjs again

- app/assets/src/app/pages/home/facebook-timeline.css
- app/assets/src/app/pages/home/facebook-timeline.js
- app/assets/src/entry/home/contact.js
- app/assets/src/entry/home/home.js
- app/assets/src/external/facebook.js
- app/config/facebook.php
- app/config/local/facebook.php
- app/controllers/home/HomeBaseController.php
- app/controllers/home/HomeController.php
- app/controllers/home/contact/ContactController.php
- app/views/home/contact/index.php
- app/views/home/index.php
> Added facebook timeline widget to home page and contact page

- app/jobs/TransferUploadJob.php
- app/serviceProviders/upload/UploadManager.php
Means that transfer of uploaded files to the filestore is asynchronous.
(Closes #789)
> Added TransferUploadJob and updated UploadManager to use it

- app/commands/LiveItemsCacheUpdateCommand.php
- app/commands/PopularItemsCacheUpdateCommand.php
- app/commands/PromotedItemsCacheUpdateCommand.php
- app/commands/RecentItemsCacheUpdateCommand.php
- app/config/custom.php
- app/models/MediaItem.php
- app/start/artisan.php
(Closes https://github.com/LA1TV/Website/issues/127)
> Cache popular items asynchronously

- app/assets/src/app/pages/home/home-page.js
- app/assets/src/app/pages/home/playlist-element.css
- app/assets/src/app/pages/home/playlist.js
- app/views/fragments/home/playlist.php
- app/views/home/index.php
> Gap between media items, increased facebook and twitter height, and remove promo autoplay

- app/models/Show.php
> Side banners and cover now only shown for latest series on show page

- app/commands/ClearTempChunksCommand.php
- app/serviceProviders/upload/UploadManager.php
- app/start/artisan.php
> Temp upload chunks are now removed in cron job

- app/assets/src/app/components/credit-input.js
- app/assets/src/app/pages/admin/media-edit-page.js
- app/assets/src/app/pages/admin/playlist-edit-page.js
- app/controllers/home/admin/media/MediaController.php
- app/controllers/home/admin/playlists/PlaylistsController.php
- app/controllers/home/admin/productionRoles/ProductionRolesController.php
- app/database/seeds/ProductionRolesSeeder.php
- app/helpers/reorderableList/PlaylistCreditsReordableList.php
- app/models/Credit.php
- app/models/Playlist.php
- app/models/ProductionRolePlaylist.php
- app/views/home/admin/playlists/edit.php
> Added credits to playlists

- app/commands/ClearOldSessionsCommand.php
- app/helpers/MySessionMiddleware.php
- app/start/artisan.php
> Session garbage collection now handled in cron job

- app/controllers/home/guide/GuideController.php
- app/controllers/home/liveStream/LiveStreamController.php
- app/controllers/home/player/PlayerController.php
- app/controllers/home/playlist/PlaylistController.php
- app/controllers/home/playlists/PlaylistsController.php
- app/controllers/home/show/ShowController.php
- app/controllers/home/shows/ShowsController.php
- app/serviceProviders/upload/UploadManager.php
> Lots of caching

- app/assets/src/app/pages/home/browser-notification-manager.js
Was setting url instead of tag.
> Fix initial "Notifications Enabled" notification

- app/models/MediaItemVideo.php
> Player info urls now cached with respect to domain

- app/controllers/home/HomeBaseController.php
- app/controllers/home/admin/AdminBaseController.php
- app/views/layouts/base.blade.php
Might have some strange issues for the embed domain, and people shouldn't be adding the embed domain as a web app anyway.
> Only enable web app capability for front end and cms

- app/api/transformers/MediaItemTransformer.php
- app/controllers/home/player/PlayerController.php
- app/models/MediaItem.php
- app/routes.php
This will redirect to the media item in its default playlists.
Closes #844
> Add "siteUrl" to media item in media item api responses

- app/controllers/home/HomeController.php
I.e. show more most popular when don't have many recent items
> Always show 10 media items on home page

- app/assets/src/app/default-ajax-select.js
- app/assets/src/app/pages/admin/live-streams-edit-page.js
- app/assets/src/app/pages/home/live-stream-page.js
- app/controllers/home/admin/livestreams/LiveStreamsController.php
- app/controllers/home/admin/media/MediaController.php
- app/controllers/home/liveStream/LiveStreamController.php
- app/database/migrations/2016_04_24_133544_add inherited_live_media_item_id to live_streams.php
- app/models/LiveStream.php
- app/views/home/admin/livestreams/edit.php
- app/views/home/liveStream/index.php
> Added inherited live media item live stream support

- app/controllers/home/liveStream/LiveStreamController.php
> Cache live stream schedule info

- app/models/MediaItem.php
Currently everything requires a lock and lock timeout errors are occurring.
> Only get exclusive lock when registering views if necessary

- app/assets/src/app/player-controller.js
- app/models/PlaybackHistory.php
Also cache the results for a bit longer.
This should reduce the load on the server a bit.
> Increase the time between watching now updates

- app/database/seeds/QualityDefinitionsSeeder.php
Adds 4k and 1440p to website seed DB.
> Added 4k and 1440p to DB seed.

- app/assets/src/app/components/player.js
- app/helpers/URLHelpers.php
- app/views/home/contact/index.php
- app/views/layouts/home/body.blade.php
Add `rel="noopener"` to external links. See https://mathiasbynens.github.io/rel-noopener/
> Add rel="noopener" to external hyperlinks

- app/controllers/embed/EmbedController.php
So we need to be able to set the video to complete flush mode so just the clapper player is on screen, Im not sure on my logic, here for review:)
> Enable use of hideBottomBar in flush mode
